import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Dataset, Insight } from '@/types';
import { formatDateTime } from '@/utils/formatDate';

export const generatePDFReport = (dataset: Dataset, insight: Insight, generatorName: string = 'Authorized System User') => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let cursorY = 20;

  // --- HELPER: Draw Header Branding ---
  const drawHeader = () => {
    // Top Bar
    doc.setFillColor(5, 150, 105); // emerald-600
    doc.rect(0, 0, pageWidth, 40, 'F');
    
    // Logo Placeholder / Text
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(24);
    doc.text('NEXUS', margin, 25);
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text('AGRIRISE AFRICA', margin, 32);
    
    // Report Title
    doc.setFontSize(14);
    doc.text('INTELLIGENCE REPORT', pageWidth - margin - 60, 25);
    
    doc.setFontSize(8);
    doc.text(`REF: NX-${Math.floor(Math.random() * 100000)}`, pageWidth - margin - 60, 32);
    
    cursorY = 55;
  };

  // --- HELPER: Draw Histogram ---
  const drawHistogram = (x: number, y: number, width: number, height: number) => {
    const data = [45, 60, 85, 30, 55, 75];
    const barWidth = (width / data.length) - 5;
    const maxVal = Math.max(...data);
    
    doc.setDrawColor(200, 200, 200);
    doc.line(x, y, x + width, y); // X-axis
    doc.line(x, y, x, y - height); // Y-axis
    
    data.forEach((val, i) => {
      const barHeight = (val / maxVal) * height;
      doc.setFillColor(5, 150, 105, 0.8);
      doc.rect(x + (i * (barWidth + 5)) + 2, y - barHeight, barWidth, barHeight, 'F');
    });
    
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('Dataset Analytics (Trend Distribution)', x + width/2, y + 10, { align: 'center' });
  };

  // --- HELPER: Draw Pie Chart ---
  const drawPieChart = (x: number, y: number, radius: number) => {
    // jsPDF doesn't have a native pie chart, so we use circle segments or stylized markers
    doc.setDrawColor(5, 150, 105);
    doc.setLineWidth(0.5);
    doc.circle(x, y, radius, 'S');
    
    // Stylized cross for segments
    doc.line(x, y - radius, x, y + radius);
    doc.line(x - radius, y, x + radius, y);
    
    // Legend
    doc.setFontSize(8);
    const legendX = x + radius + 10;
    
    const segments = [
      { label: 'Market Stability', color: [5, 150, 105] },
      { label: 'Climate Resilience', color: [59, 130, 246] },
      { label: 'Supply Integrity', color: [245, 158, 11] }
    ];
    
    segments.forEach((s, i) => {
      doc.setFillColor(s.color[0], s.color[1], s.color[2]);
      doc.rect(legendX, y - radius + (i * 8), 4, 4, 'F');
      doc.text(s.label, legendX + 7, y - radius + (i * 8) + 3);
    });
  };

  drawHeader();

  // --- SECTION 1: IDENTITY & METADATA ---
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text('I. REPORT AUTHENTICATION', margin, cursorY);
  cursorY += 8;
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const metadata = [
    ['GENERATED BY:', generatorName.toUpperCase()],
    ['DATASET SOURCE:', dataset.name],
    ['COUNTRY ORIGIN:', dataset.country || 'PAN-AFRICAN'],
    ['GENERATION DATE:', formatDateTime(new Date().toISOString())]
  ];
  
  autoTable(doc, {
    startY: cursorY,
    body: metadata,
    theme: 'plain',
    styles: { fontSize: 8, cellPadding: 2 },
    columnStyles: { 0: { fontStyle: 'bold', width: 40 } },
    margin: { left: margin }
  });
  cursorY = (doc as any).lastAutoTable.finalY + 15;

  // --- SECTION 2: DATA VISUALIZATION ---
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('II. ANALYTICAL VISUALIZATION', margin, cursorY);
  cursorY += 25;
  
  drawHistogram(margin + 5, cursorY, 70, 40);
  drawPieChart(pageWidth - margin - 50, cursorY - 20, 15);
  cursorY += 25;

  // --- SECTION 3: MARKET INTELLIGENCE & IMPACT ---
  cursorY += 15;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('III. IMPACT ANALYSIS', margin, cursorY);
  cursorY += 8;
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const impactText = `Primary risk level evaluated as ${insight.risk_level.toUpperCase()}. The core analysis suggests a ${insight.trend.toLowerCase()} movement. This affects approximately 15% of regional agribusiness output in the specified sector.`;
  const impactLines = doc.splitTextToSize(impactText, pageWidth - (margin * 2));
  doc.text(impactLines, margin, cursorY);
  cursorY += (impactLines.length * 5) + 12;

  // --- SECTION 4: STRATEGIC RECOMMENDATIONS ---
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('IV. STRATEGIC RECOMMENDATIONS', margin, cursorY);
  cursorY += 8;
  
  doc.setFont('helvetica', 'normal');
  const recommendations = [
    '• Immediate diversification of commodity sourcing to mitigate supply chain volatility.',
    '• Activation of climate-contingent insurance protocols for identified high-risk zones.',
    '• Implementation of blockchain-based tracking for cross-border arbitrage verification.',
    '• Strategic reserve allocation based on AI-predicted price floor transitions.'
  ];
  recommendations.forEach(rec => {
    doc.text(rec, margin, cursorY);
    cursorY += 6;
  });
  cursorY += 10;

  // --- SECTION 5: RESOLUTION GUIDELINES ---
  if (cursorY > pageHeight - 60) { doc.addPage(); cursorY = 30; }
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('V. STEP-BY-STEP RESOLUTION GUIDELINES', margin, cursorY);
  cursorY += 8;
  
  const steps = [
    '1. Audit internal datasets against Nexus AI generated trend parameters.',
    '2. Consult with regional agribusiness leads to align on predictive insights.',
    '3. Execute procurement adjustments within 48 hours of trend confirmation.',
    '4. Document all cross-border transactions for automated regulatory compliance.'
  ];
  doc.setFont('helvetica', 'normal');
  steps.forEach(step => {
    doc.text(step, margin, cursorY);
    cursorY += 6;
  });
  cursorY += 20;

  // --- SECTION 6: AUTHORIZATION & VALIDATION ---
  const signatureY = pageHeight - 60;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, signatureY, pageWidth - margin, signatureY);
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('AUTHORIZED VALIDATION CODE:', margin, signatureY + 10);
  
  doc.setFont('courier', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  const authCode = `NX-AUTH-${Buffer.from(insight.id).toString('base64').substring(0, 12).toUpperCase()}`;
  doc.text(authCode, margin, signatureY + 18);
  
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Lead Manager Signature Placeholder:', pageWidth - margin - 60, signatureY + 10);
  doc.setDrawColor(0, 0, 0);
  doc.line(pageWidth - margin - 60, signatureY + 30, pageWidth - margin, signatureY + 30);
  doc.setFontSize(7);
  doc.text('Augustin Nkundimana / Lead Analyst', pageWidth - margin - 60, signatureY + 35);

  // SAVE THE PDF
  const safeName = dataset.name.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  doc.save(`Nexus_Intelligence_Report_${safeName}.pdf`);
};
