import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Dataset, Insight } from '@/types';
import { formatDateTime } from '@/utils/formatDate';

export const generatePDFReport = (dataset: Dataset, insight: Insight) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let cursorY = 20;

  // Helper for drawing horizontal lines
  const drawLine = () => {
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, cursorY, pageWidth - margin, cursorY);
    cursorY += 10;
  };

  // --- SECTION 1: HEADER ---
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(5, 150, 105); // emerald-600
  doc.text('Nexus AgriRise Africa', margin, cursorY);
  cursorY += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(14);
  doc.setTextColor(100, 100, 100);
  doc.text('Market Intelligence Report', margin, cursorY);
  cursorY += 15;

  doc.setFontSize(10);
  doc.text('AI-driven Agribusiness Intelligence System for Africa', margin, cursorY);
  cursorY += 5;
  doc.text(`Generated on ${formatDateTime(new Date().toISOString())}`, margin, cursorY);
  cursorY += 10;

  drawLine();

  // --- SECTION 2: DATASET INFORMATION ---
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text('1. Dataset Information', margin, cursorY);
  cursorY += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const datasetInfo = [
    ['Dataset Name', dataset.name],
    ['Country', dataset.country || 'Global'],
    ['Type', dataset.type || 'CSV'],
    ['Upload Date', formatDateTime(dataset.created_at)],
  ];

  autoTable(doc, {
    startY: cursorY,
    head: [['Field', 'Value']],
    body: datasetInfo,
    theme: 'striped',
    headStyles: { fillColor: [5, 150, 105] }, // use numeric color for stability
    margin: { left: margin, right: margin },
  });
  cursorY = (doc as any).lastAutoTable.finalY + 15;

  // --- SECTION 3: MARKET SUMMARY ---
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('2. Market Summary', margin, cursorY);
  cursorY += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const summaryLines = doc.splitTextToSize(insight.summary, pageWidth - (margin * 2));
  doc.text(summaryLines, margin, cursorY);
  cursorY += (summaryLines.length * 5) + 15;

  // --- SECTION 4: RISK ASSESSMENT ---
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('3. Risk Assessment', margin, cursorY);
  cursorY += 10;

  const riskLevel = insight.risk_level.toUpperCase();
  let riskColor = [100, 100, 100]; // Gray
  if (riskLevel === 'LOW') riskColor = [5, 150, 105]; // Green
  if (riskLevel === 'MEDIUM') riskColor = [245, 158, 11]; // Yellow
  if (riskLevel === 'HIGH') riskColor = [220, 38, 38]; // Red

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(riskColor[0], riskColor[1], riskColor[2]);
  doc.text(`Risk Level: ${riskLevel}`, margin, cursorY);
  cursorY += 15;

  // --- SECTION 5: PRICE TREND ANALYSIS ---
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('4. Price Trend Analysis', margin, cursorY);
  cursorY += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const trendLines = doc.splitTextToSize(insight.trend, pageWidth - (margin * 2));
  doc.text(trendLines, margin, cursorY);
  cursorY += (trendLines.length * 5) + 15;

  // --- SECTION 6: CROSS-BORDER OPPORTUNITIES ---
  const crossBorder = (insight as any).cross_border_opportunity || 'No specific cross-border opportunities identified for this dataset.';
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('5. Cross-Border Opportunity Insights', margin, cursorY);
  cursorY += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const cbLines = doc.splitTextToSize(crossBorder, pageWidth - (margin * 2));
  doc.text(cbLines, margin, cursorY);
  cursorY += (cbLines.length * 5) + 15;

  // --- SECTION 7: FOOTER ---
  const totalPages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      'Generated by Nexus AgriRise Africa AI Intelligence Engine',
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth - margin,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'right' }
    );
  }

  // SAVE THE PDF
  const safeName = dataset.name.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  doc.save(`Nexus_Report_${safeName}.pdf`);
};
